apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata: 
      labels:
        app: cache
    spec: 
      containers:
        - name: cache
          image: redis:6.2-alpine

---

apiVersion: v1
kind: Service
metadata:
  name: cache-service
spec:
  selector: 
    app: cache
  ports:
    - port: 6379
      targetPort: 6379
  type: LoadBalancer