version: "3.8"
services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_DATABASE=weather
  webapi:
    build: ./Docker.WebApi
    ports:
      - '7230:80'
      - '7231:443'
    depends_on:
      - mongodb