version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  webapi:
    build: ./Docker.WebApi
    ports:
      - '7230:80'
      - '7231:443'
    depends_on:
      - db

volumes:
  db:
    driver: local