version: "3.8"
services:
  webapi:
    build: ./Docker.WebApi
    ports:
      - '7230:80'
      - '7231:443'
    #environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=Coucou123
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=app/https/aspnetapp.pfx
    #volumes: 
      #- ./https:/app/https/

#volumes: 
  #data:
  #logs: